_welcome:
    path:     /
    defaults: { _controller: AcmeDemoBundle:TestKnpmenu:index }

_demo_secured:
    resource: "@AcmeDemoBundle/Controller/SecuredController.php"
    type:     annotation

_demo:
    resource: "@AcmeDemoBundle/Controller/DemoController.php"
    type:     annotation
    prefix:   /demo

test_knpmenu:
    path: /knpmenu
    defaults: { _controller: AcmeDemoBundle:TestKnpmenu:index }
